name: PowerPlay FYI
favicon: null
layout_spectrum: 0.7680758200585842
typography_spectrum: 0.969653154257685
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6335118156857789
  lightness: 0.20024747797288
  saturation: 0.1820678119547665
  rhythmicContrast: 0.7032311132643372
purpose: []
